#loc = loc(unknown)
#loc1 = loc("leaves[0]")
#loc2 = loc("leaves[1]")
#loc3 = loc("leaves[2]")
#loc4 = loc("leaves[3]")
#loc5 = loc("leaves[4]")
#loc6 = loc("leaves[5]")
#loc7 = loc("leaves[6]")
#loc8 = loc("leaves[7]")
#loc9 = loc("leaves[8]")
module @jit_avail attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2xi32> loc("leaves[0]"), %arg1: tensor<2xi32> loc("leaves[1]"), %arg2: tensor<i32> loc("leaves[2]"), %arg3: tensor<i32> loc("leaves[3]"), %arg4: tensor<2xf32> loc("leaves[4]"), %arg5: tensor<2xi1> loc("leaves[5]"), %arg6: tensor<i1> loc("leaves[6]"), %arg7: tensor<i1> loc("leaves[7]"), %arg8: tensor<i32> loc("leaves[8]")) -> (tensor<2xi1> {jax.result_info = "result"}) {
    %0 = call @get_avail_actions(%arg0, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8) : (tensor<2xi32>, tensor<2xi32>, tensor<i32>, tensor<i32>, tensor<2xf32>, tensor<2xi1>, tensor<i1>, tensor<i1>, tensor<i32>) -> tensor<2xi1> loc(#loc10)
    return %0 : tensor<2xi1> loc(#loc11)
  } loc(#loc)
  func.func private @get_avail_actions(%arg0: tensor<2xi32> loc(unknown), %arg1: tensor<2xi32> loc(unknown), %arg2: tensor<i32> loc(unknown), %arg3: tensor<i32> loc(unknown), %arg4: tensor<2xf32> loc(unknown), %arg5: tensor<2xi1> loc(unknown), %arg6: tensor<i1> loc(unknown), %arg7: tensor<i1> loc(unknown), %arg8: tensor<i32> loc(unknown)) -> tensor<2xi1> {
    %c = stablehlo.constant dense<true> : tensor<i1> loc(#loc)
    %c_0 = stablehlo.constant dense<false> : tensor<i1> loc(#loc)
    %0 = stablehlo.broadcast_in_dim %c_0, dims = [] : (tensor<i1>) -> tensor<2xi1> loc(#loc13)
    %1 = stablehlo.broadcast_in_dim %c, dims = [] : (tensor<i1>) -> tensor<2xi1> loc(#loc13)
    %2 = call @_where(%arg7, %0, %1) : (tensor<i1>, tensor<2xi1>, tensor<2xi1>) -> tensor<2xi1> loc(#loc14)
    return %2 : tensor<2xi1> loc(#loc)
  } loc(#loc17)
  func.func private @_where(%arg0: tensor<i1> loc(unknown), %arg1: tensor<2xi1> loc(unknown), %arg2: tensor<2xi1> loc(unknown)) -> tensor<2xi1> {
    %0 = stablehlo.select %arg0, %arg1, %arg2 : tensor<i1>, tensor<2xi1> loc(#loc16)
    return %0 : tensor<2xi1> loc(#loc)
  } loc(#loc18)
} loc(#loc)
#loc10 = loc("jit(avail)/jit(get_avail_actions)")
#loc11 = loc("jit(avail)")
#loc12 = loc("jit(avail)/jit")
#loc13 = loc("broadcast_in_dim")
#loc14 = loc("jit(_where)")
#loc15 = loc("jit")
#loc16 = loc("select_n")
#loc17 = loc("jit:"(#loc12))
#loc18 = loc("jit:"(#loc15))
