#loc = loc(unknown)
#loc1 = loc("leaves[0]")
#loc2 = loc("leaves[1]")
#loc3 = loc("leaves[2]")
#loc4 = loc("leaves[3]")
#loc5 = loc("leaves[4]")
#loc6 = loc("leaves[5]")
#loc7 = loc("leaves[6]")
#loc8 = loc("leaves[7]")
module @jit_avail attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2x13xi1> loc("leaves[0]"), %arg1: tensor<13xi32> loc("leaves[1]"), %arg2: tensor<i32> loc("leaves[2]"), %arg3: tensor<2xf32> loc("leaves[3]"), %arg4: tensor<2xi1> loc("leaves[4]"), %arg5: tensor<2xi1> loc("leaves[5]"), %arg6: tensor<i1> loc("leaves[6]"), %arg7: tensor<i32> loc("leaves[7]")) -> (tensor<2x13xi1> {jax.result_info = "result"}) {
    %0 = call @get_avail_actions(%arg0, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7) : (tensor<2x13xi1>, tensor<13xi32>, tensor<i32>, tensor<2xf32>, tensor<2xi1>, tensor<2xi1>, tensor<i1>, tensor<i32>) -> tensor<2x13xi1> loc(#loc9)
    return %0 : tensor<2x13xi1> loc(#loc10)
  } loc(#loc)
  func.func private @get_avail_actions(%arg0: tensor<2x13xi1> loc(unknown), %arg1: tensor<13xi32> loc(unknown), %arg2: tensor<i32> loc(unknown), %arg3: tensor<2xf32> loc(unknown), %arg4: tensor<2xi1> loc(unknown), %arg5: tensor<2xi1> loc(unknown), %arg6: tensor<i1> loc(unknown), %arg7: tensor<i32> loc(unknown)) -> tensor<2x13xi1> {
    %c = stablehlo.constant dense<false> : tensor<i1> loc(#loc)
    %0 = stablehlo.broadcast_in_dim %c, dims = [] : (tensor<i1>) -> tensor<2x13xi1> loc(#loc12)
    %1 = call @_where(%arg6, %0, %arg0) : (tensor<i1>, tensor<2x13xi1>, tensor<2x13xi1>) -> tensor<2x13xi1> loc(#loc13)
    return %1 : tensor<2x13xi1> loc(#loc)
  } loc(#loc16)
  func.func private @_where(%arg0: tensor<i1> loc(unknown), %arg1: tensor<2x13xi1> loc(unknown), %arg2: tensor<2x13xi1> loc(unknown)) -> tensor<2x13xi1> {
    %0 = stablehlo.select %arg0, %arg1, %arg2 : tensor<i1>, tensor<2x13xi1> loc(#loc15)
    return %0 : tensor<2x13xi1> loc(#loc)
  } loc(#loc17)
} loc(#loc)
#loc9 = loc("jit(avail)/jit(get_avail_actions)")
#loc10 = loc("jit(avail)")
#loc11 = loc("jit(avail)/jit")
#loc12 = loc("broadcast_in_dim")
#loc13 = loc("jit(_where)")
#loc14 = loc("jit")
#loc15 = loc("select_n")
#loc16 = loc("jit:"(#loc11))
#loc17 = loc("jit:"(#loc14))
