#loc = loc(unknown)
#loc1 = loc("leaves[0]")
#loc2 = loc("leaves[1]")
#loc3 = loc("leaves[2]")
#loc4 = loc("leaves[3]")
#loc5 = loc("leaves[4]")
#loc6 = loc("leaves[5]")
#loc7 = loc("leaves[6]")
#loc8 = loc("leaves[7]")
#loc9 = loc("leaves[8]")
#loc10 = loc("leaves[9]")
#loc11 = loc("leaves[10]")
#loc12 = loc("leaves[11]")
#loc13 = loc("leaves[12]")
#loc14 = loc("leaves[13]")
#loc28 = loc("scatter")
#loc32 = loc("scatter:"(#loc28))
module @jit_avail attributes {jax.uses_shape_polymorphism = false, mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<3xi32> loc("leaves[0]"), %arg1: tensor<i32> loc("leaves[1]"), %arg2: tensor<i32> loc("leaves[2]"), %arg3: tensor<2x2xi32> loc("leaves[3]"), %arg4: tensor<2xf32> loc("leaves[4]"), %arg5: tensor<i32> loc("leaves[5]"), %arg6: tensor<i32> loc("leaves[6]"), %arg7: tensor<i32> loc("leaves[7]"), %arg8: tensor<4xi32> loc("leaves[8]"), %arg9: tensor<2xi1> loc("leaves[9]"), %arg10: tensor<i32> loc("leaves[10]"), %arg11: tensor<2xi1> loc("leaves[11]"), %arg12: tensor<i1> loc("leaves[12]"), %arg13: tensor<i32> loc("leaves[13]")) -> (tensor<4xi1> {jax.result_info = "result"}) {
    %0 = call @get_avail_actions(%arg0, %arg1, %arg2, %arg3, %arg4, %arg5, %arg6, %arg7, %arg8, %arg9, %arg10, %arg11, %arg12, %arg13) : (tensor<3xi32>, tensor<i32>, tensor<i32>, tensor<2x2xi32>, tensor<2xf32>, tensor<i32>, tensor<i32>, tensor<i32>, tensor<4xi32>, tensor<2xi1>, tensor<i32>, tensor<2xi1>, tensor<i1>, tensor<i32>) -> tensor<4xi1> loc(#loc15)
    return %0 : tensor<4xi1> loc(#loc16)
  } loc(#loc)
  func.func private @get_avail_actions(%arg0: tensor<3xi32> loc(unknown), %arg1: tensor<i32> loc(unknown), %arg2: tensor<i32> loc(unknown), %arg3: tensor<2x2xi32> loc(unknown), %arg4: tensor<2xf32> loc(unknown), %arg5: tensor<i32> loc(unknown), %arg6: tensor<i32> loc(unknown), %arg7: tensor<i32> loc(unknown), %arg8: tensor<4xi32> loc(unknown), %arg9: tensor<2xi1> loc(unknown), %arg10: tensor<i32> loc(unknown), %arg11: tensor<2xi1> loc(unknown), %arg12: tensor<i1> loc(unknown), %arg13: tensor<i32> loc(unknown)) -> tensor<4xi1> {
    %c = stablehlo.constant dense<false> : tensor<i1> loc(#loc)
    %c_0 = stablehlo.constant dense<3> : tensor<i32> loc(#loc)
    %c_1 = stablehlo.constant dense<1> : tensor<i32> loc(#loc)
    %c_2 = stablehlo.constant dense<4> : tensor<i32> loc(#loc)
    %c_3 = stablehlo.constant dense<true> : tensor<i1> loc(#loc)
    %cst = stablehlo.constant dense<0xFF800000> : tensor<f32> loc(#loc)
    %c_4 = stablehlo.constant dense<2> : tensor<i32> loc(#loc)
    %c_5 = stablehlo.constant dense<0> : tensor<i32> loc(#loc)
    %0 = stablehlo.convert %arg12 : (tensor<i1>) -> tensor<i32> loc(#loc18)
    %1 = "stablehlo.case"(%0) ({
      %2 = stablehlo.compare LT, %arg6, %c_5, SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc20)
      %3 = stablehlo.add %arg6, %c_4 : tensor<i32> loc(#loc21)
      %4 = stablehlo.select %2, %3, %arg6 : tensor<i1>, tensor<i32> loc(#loc22)
      %5 = stablehlo.dynamic_slice %arg4, %4, sizes = [1] : (tensor<2xf32>, tensor<i32>) -> tensor<1xf32> loc(#loc23)
      %6 = stablehlo.reshape %5 : (tensor<1xf32>) -> tensor<f32> loc(#loc24)
      %7 = stablehlo.reduce(%arg4 init: %cst) applies stablehlo.maximum across dimensions = [0] : (tensor<2xf32>, tensor<f32>) -> tensor<f32> loc(#loc25)
      %8 = stablehlo.broadcast_in_dim %c_3, dims = [] : (tensor<i1>) -> tensor<4xi1> loc(#loc26)
      %9 = stablehlo.compare LT, %arg7, %c_5, SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc20)
      %10 = stablehlo.add %arg7, %c_2 : tensor<i32> loc(#loc21)
      %11 = stablehlo.select %9, %10, %arg7 : tensor<i1>, tensor<i32> loc(#loc22)
      %12 = stablehlo.dynamic_slice %arg8, %11, sizes = [1] : (tensor<4xi32>, tensor<i32>) -> tensor<1xi32> loc(#loc23)
      %13 = stablehlo.reshape %12 : (tensor<1xi32>) -> tensor<i32> loc(#loc24)
      %14 = stablehlo.compare LT, %13, %c_2, SIGNED : (tensor<i32>, tensor<i32>) -> tensor<i1> loc(#loc20)
      %15 = stablehlo.broadcast_in_dim %c_1, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc26)
      %16 = "stablehlo.scatter"(%8, %15, %14) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
      ^bb0(%arg14: tensor<i1> loc("scatter:"(#loc28)), %arg15: tensor<i1> loc("scatter:"(#loc28))):
        stablehlo.return %arg15 : tensor<i1> loc(#loc27)
      }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc27)
      %17 = stablehlo.compare LT, %6, %7, FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1> loc(#loc20)
      %18 = stablehlo.broadcast_in_dim %c_5, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc26)
      %19 = "stablehlo.scatter"(%16, %18, %17) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
      ^bb0(%arg14: tensor<i1> loc("scatter:"(#loc28)), %arg15: tensor<i1> loc("scatter:"(#loc28))):
        stablehlo.return %arg15 : tensor<i1> loc(#loc27)
      }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc27)
      %20 = stablehlo.compare EQ, %6, %7, FLOAT : (tensor<f32>, tensor<f32>) -> tensor<i1> loc(#loc29)
      %21 = stablehlo.broadcast_in_dim %c_0, dims = [] : (tensor<i32>) -> tensor<1xi32> loc(#loc26)
      %22 = "stablehlo.scatter"(%19, %21, %20) <{indices_are_sorted = true, scatter_dimension_numbers = #stablehlo.scatter<inserted_window_dims = [0], scatter_dims_to_operand_dims = [0]>, unique_indices = true}> ({
      ^bb0(%arg14: tensor<i1> loc("scatter:"(#loc28)), %arg15: tensor<i1> loc("scatter:"(#loc28))):
        stablehlo.return %arg15 : tensor<i1> loc(#loc27)
      }) : (tensor<4xi1>, tensor<1xi32>, tensor<i1>) -> tensor<4xi1> loc(#loc27)
      stablehlo.return %22 : tensor<4xi1> loc(#loc19)
    }, {
      %2 = stablehlo.broadcast_in_dim %c, dims = [] : (tensor<i1>) -> tensor<4xi1> loc(#loc30)
      stablehlo.return %2 : tensor<4xi1> loc(#loc19)
    }) : (tensor<i32>) -> tensor<4xi1> loc(#loc19)
    return %1 : tensor<4xi1> loc(#loc)
  } loc(#loc31)
} loc(#loc)
#loc15 = loc("jit(avail)/jit(get_avail_actions)")
#loc16 = loc("jit(avail)")
#loc17 = loc("jit(avail)/jit")
#loc18 = loc("convert_element_type")
#loc19 = loc("cond")
#loc20 = loc("cond/branch_0_fun/lt")
#loc21 = loc("cond/branch_0_fun/add")
#loc22 = loc("cond/branch_0_fun/select_n")
#loc23 = loc("cond/branch_0_fun/dynamic_slice")
#loc24 = loc("cond/branch_0_fun/squeeze")
#loc25 = loc("cond/branch_0_fun/reduce_max")
#loc26 = loc("cond/branch_0_fun/broadcast_in_dim")
#loc27 = loc("cond/branch_0_fun/scatter")
#loc29 = loc("cond/branch_0_fun/eq")
#loc30 = loc("cond/branch_1_fun/broadcast_in_dim")
#loc31 = loc("jit:"(#loc17))
